//
//Copyright (c) 1998,2007 Michael Toth
//Spiralcraft Inc., All Rights Reserved
//
//This package is part of the Spiralcraft project and is licensed under
//a multiple-license framework.
//
//You may not use this file except in compliance with the terms found in the
//SPIRALCRAFT-LICENSE.txt file at the top of this distribution, or available
//at http://www.spiralcraft.org/licensing/SPIRALCRAFT-LICENSE.txt.
//
//Unless otherwise agreed to in writing, this software is distributed on an
//"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
//
package spiralcraft.servlet.pages;

import spiralcraft.servlet.HttpServlet;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.ServletException;

import java.io.IOException;

import java.net.URI;
import java.net.URISyntaxException;
import java.net.MalformedURLException;

import java.util.HashMap;

import spiralcraft.vfs.Resolver;
import spiralcraft.vfs.Resource;
import spiralcraft.vfs.UnresolvableURIException;

import spiralcraft.textgen.Generator;
import spiralcraft.textgen.Element;

import spiralcraft.text.ParseException;

import spiralcraft.servlet.HttpFocus;

import spiralcraft.lang.Focus;
import spiralcraft.lang.BindException;


/**
 * <P>An HttpServlet which serves pages generated by the spiralcraft.textgen 
 *   generation engine.
 *   
 * <P>There is one GeneratorServlet per servlet context. There is one copy of
 *   each bound (compiled) page in the context.
 * 
 * @author mike
 *
 */
public class GeneratorServlet
  extends HttpServlet
{

  private final HashMap<String,ResourceEntry> resourceMap
    =new HashMap<String,ResourceEntry>();
  
  private final HttpFocus<Void> httpFocus=new HttpFocus<Void>();
  
  @Override
  protected void doGet(HttpServletRequest request,HttpServletResponse response)
    throws ServletException,IOException
  {
    try
    {
      ResourceEntry entry=getEntry(request);
      if (entry==null)
      { response.sendError(404,request.getRequestURI()+" not found");
      }
      entry.service(request,response);
    }
    catch (URISyntaxException x)
    { throw new ServletException(x.toString(),x);
    }
    catch (MalformedURLException x)
    { throw new ServletException(x.toString(),x);
    }
    catch (UnresolvableURIException x)
    { throw new ServletException(x.toString(),x);
    }
  }
  
  /**
   * Obtain a ResourceEntry for the specified request. ResourceEntries are
   *   cached for resources that exist.
   * 
   * @param request
   * @return
   */
  private ResourceEntry getEntry(HttpServletRequest request)
    throws URISyntaxException
      ,MalformedURLException
      ,UnresolvableURIException
      ,IOException
  {
    String resourcePath=request.getPathInfo();
    if (resourcePath==null)
    { resourcePath=request.getServletPath();
    }
    
    if (resourcePath==null)
    { return null;
    }
    
    ResourceEntry entry;
    synchronized (resourceMap)
    {
      entry=resourceMap.get(resourcePath);
      if (entry==null)
      { 
        URI uri
          =getServletConfig()
            .getServletContext()
              .getResource(resourcePath)
                .toURI();
        Resource resource=Resolver.getInstance().resolve(uri);
        if (resource.exists())
        { 
          entry=new ResourceEntry(resource,httpFocus);
          resourceMap.put(resourcePath,entry);
        }
        
      }
      else
      {
        if (!entry.getResource().exists())
        { 
          resourceMap.remove(resourcePath);
          entry=null;
        }
      }
    }
    
    return entry;
  }
  
 
}

class ResourceEntry
{
  private final Resource resource;
  private final Focus<?> focus;
  private long lastRead;
  private Generator generator;
  
  @SuppressWarnings("unused") // XXX Incomplete
  private Element element;
  @SuppressWarnings("unused") // XXX Incomplete
  private Exception exception;
  
  public ResourceEntry(Resource resource,HttpFocus<?> focus)
  { 
    this.resource=resource;
    this.focus=focus;
  }
  
  public Resource getResource()
  { return resource;
  }
  
  public synchronized void checkState()
    throws IOException
  {
    long lastModified=resource.getLastModified();
    if (lastModified>lastRead)
    { recompile();
    }
    lastRead=lastModified;     
  }
  
  private void recompile()
  {
    try
    { 
      generator=new Generator(resource.getURI());
      element=generator.bind(focus);
    }
    catch (IOException x)
    { exception=x;
    }
    catch (ParseException x)
    { exception=x;
    }
    catch (BindException x)
    { exception=x;
    }
  }
  
  
  
  
  public void service
    (HttpServletRequest request,HttpServletResponse response)
    throws ServletException,IOException
  {
    checkState();
  }
  
}
